# Generated by Django 5.0.1 on 2024-02-03 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0004_remove_userasset_user_delete_game_delete_userasset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(default="New Game", max_length=255)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.CharField(default="in development", max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UGAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(default="New Asset", max_length=255)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "file_path",
                    models.CharField(default="path/to/asset", max_length=255),
                ),
                ("status", models.CharField(default="pending review", max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UGGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gameName", models.CharField(max_length=255)),
                ("prompt", models.TextField()),
                ("url", models.URLField()),
                ("assetList", models.ManyToManyField(to="game.ugasset")),
                (
                    "creatorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.customuser",
                    ),
                ),
                (
                    "remraiID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
            ],
        ),
    ]
