# Generated by Django 5.0.1 on 2024-02-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="game", name="creation_date",),
        migrations.RemoveField(model_name="game", name="last_updated",),
        migrations.RemoveField(model_name="game", name="status",),
        migrations.RemoveField(model_name="game", name="user",),
        migrations.AddField(
            model_name="game",
            name="descriptions",
            field=models.TextField(default="default_descriptions"),
        ),
        migrations.AddField(
            model_name="game",
            name="search_descriptions",
            field=models.TextField(default="default_search_descriptions"),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_name",
            field=models.CharField(default="default_name", max_length=255),
        ),
        migrations.CreateModel(
            name="Image_Assets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(default="default_asset_name", max_length=255),
                ),
                ("path", models.CharField(default="default_path", max_length=255)),
                ("descriptions", models.TextField(default="default_descriptions")),
                ("dimensions_x", models.CharField(default="512", max_length=10)),
                ("dimensions_y", models.CharField(default="512", max_length=10)),
                ("type", models.CharField(default="1", max_length=2)),
                ("style", models.CharField(default="fantasy-art", max_length=50)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_asset",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sound_Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "soundName",
                    models.CharField(default="default_soundName", max_length=255),
                ),
                ("path", models.CharField(default="default_path", max_length=255)),
                ("descriptions", models.TextField(default="default_descriptions")),
                ("duration", models.CharField(default="10", max_length=50)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sound_assets",
                        to="game.game",
                    ),
                ),
            ],
        ),
    ]
