# Generated by Django 4.2.9 on 2024-02-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_remove_game_creation_date_remove_game_last_updated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uggame", old_name="remraiID", new_name="gameid",
        ),
    ]
