# Generated by Django 5.0.1 on 2024-02-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_rename_remraiid_uggame_gameid"),
    ]

    operations = [
        migrations.DeleteModel(name="UGGame",),
    ]
