# Generated by Django 5.0.1 on 2024-02-10 05:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_delete_uggame"),
        ("user", "0004_remove_userasset_user_delete_game_delete_userasset"),
    ]

    operations = [
        migrations.CreateModel(
            name="UGGame",
            fields=[
                (
                    "gameid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("game_title", models.CharField(max_length=255)),
                ("prompt", models.TextField()),
                ("url", models.URLField()),
                ("thumbnail_url", models.URLField()),
                ("asset_list", models.ManyToManyField(to="game.ugasset")),
                (
                    "creatorid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.customuser",
                    ),
                ),
                (
                    "default_gameid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
            ],
        ),
    ]
