# Generated by Django 5.0.1 on 2024-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_usercredit_user_remove_userprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_premium",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has premium subscription",
            ),
        ),
    ]
